---
apiVersion: v1
kind: Service
metadata:
  name: featureflags-db
  labels:
    app: featureflags-db
spec:
  type: NodePort
  selector:
    app: featureflags-db
  ports:
  - protocol: TCP
    port: 5432
    name: jdbc-postgresql

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: featureflags-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: featureflags-db
    spec:
      containers:
      - name: featureflags-db
        image: quiram/featureflags-db
        ports:
        - containerPort: 5432
