---
apiVersion: v1
kind: Service
metadata:
  name: featureflags-db
  labels:
    app: featureflags-db
spec:
  type: NodePort
  selector:
    app: featureflags-db
  ports:
  - protocol: TCP
    port: 3306
    name: mysql

