version: '3'
services:
  jenkins:
    image: quiram/jenkins-base
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "jenkins_base_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    network_mode: "host"

volumes:
  jenkins_base_home:
